/*
* @Author: shu.wen
* @Date:   2017-04-28 21:38:44
* @Last Modified by:   shu.wen
* @Last Modified time: 2017-05-05 01:15:11
*/

SELECT COUNT() FROM JDATA_USER_TBL;
-- 105321
SELECT COUNT() FROM JDATA_PRODUCT_TBL;
-- 24187
SELECT COUNT() FROM JDATA_COMMENT_TBL;
-- 558552
SELECT COUNT() FROM JDATA_ACTION_TBL;
-- 50601736

-- target generation
drop table if exists LABEL_0411_0415;
create table LABEL_0411_0415 as
select
USER_ID,
SKU_ID,
MAX(case when type = 4 then 1 else 0 end) as Y
from (
select *
from JDATA_ACTION_TBL
where 1=1
and time >= date('2016-04-11')
and time <  date('2016-04-16')
and CATE = '8'
and TYPE = '4'
)
group by
USER_ID,
SKU_ID;

SELECT COUNT() FROM LABEL_0411_0415;
-- 1385


-- SKU level conversion rates
drop table if exists SKU_CONVERSION_RATES_0201_0410;
create table SKU_CONVERSION_RATES_0201_0410 as
select
SKU_ID
,SUM(CASE WHEN TYPE = "1" THEN 1 ELSE 0 END) AS SKU_TYPE_1_CNT
,SUM(CASE WHEN TYPE = "2" THEN 1 ELSE 0 END) AS SKU_TYPE_2_CNT
,SUM(CASE WHEN TYPE = "3" THEN 1 ELSE 0 END) AS SKU_TYPE_3_CNT
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END) AS SKU_TYPE_4_CNT
,SUM(CASE WHEN TYPE = "5" THEN 1 ELSE 0 END) AS SKU_TYPE_5_CNT
,SUM(CASE WHEN TYPE = "6" THEN 1 ELSE 0 END) AS SKU_TYPE_6_CNT
,SUM(CASE WHEN TYPE = "1" THEN 1 ELSE 0 END)*1.0 / COUNT() AS SKU_TYPE_1_RATE
,SUM(CASE WHEN TYPE = "2" THEN 1 ELSE 0 END)*1.0 / COUNT() AS SKU_TYPE_2_RATE
,SUM(CASE WHEN TYPE = "3" THEN 1 ELSE 0 END)*1.0 / COUNT() AS SKU_TYPE_3_RATE
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END)*1.0 / COUNT() AS SKU_TYPE_4_RATE
,SUM(CASE WHEN TYPE = "5" THEN 1 ELSE 0 END)*1.0 / COUNT() AS SKU_TYPE_5_RATE
,SUM(CASE WHEN TYPE = "6" THEN 1 ELSE 0 END)*1.0 / COUNT() AS SKU_TYPE_6_RATE
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END)*1.0 / SUM(CASE WHEN TYPE = "1" THEN 1 ELSE 0 END) AS SKU_TYPE_1_4_RATE
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END)*1.0 / SUM(CASE WHEN TYPE = "2" THEN 1 ELSE 0 END) AS SKU_TYPE_2_4_RATE
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END)*1.0 / SUM(CASE WHEN TYPE = "3" THEN 1 ELSE 0 END) AS SKU_TYPE_3_4_RATE
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END)*1.0 / SUM(CASE WHEN TYPE = "5" THEN 1 ELSE 0 END) AS SKU_TYPE_5_4_RATE
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END)*1.0 / SUM(CASE WHEN TYPE = "6" THEN 1 ELSE 0 END) AS SKU_TYPE_6_4_RATE
from JDATA_ACTION_TBL
where time <= DATE('2016-04-10')
group by SKU_ID;

select count() from SKU_CONVERSION_RATES_0201_0410
-- 27907

-- Brand level conversion rates
drop table if exists BRAND_CONVERSION_RATES_0201_0410;
create table BRAND_CONVERSION_RATES_0201_0410 as
select
BRAND
,SUM(CASE WHEN TYPE = "1" THEN 1 ELSE 0 END) AS BRAND_TYPE_1_CNT
,SUM(CASE WHEN TYPE = "2" THEN 1 ELSE 0 END) AS BRAND_TYPE_2_CNT
,SUM(CASE WHEN TYPE = "3" THEN 1 ELSE 0 END) AS BRAND_TYPE_3_CNT
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END) AS BRAND_TYPE_4_CNT
,SUM(CASE WHEN TYPE = "5" THEN 1 ELSE 0 END) AS BRAND_TYPE_5_CNT
,SUM(CASE WHEN TYPE = "6" THEN 1 ELSE 0 END) AS BRAND_TYPE_6_CNT
,SUM(CASE WHEN TYPE = "1" THEN 1 ELSE 0 END)*1.0 / COUNT() AS BRAND_TYPE_1_RATE
,SUM(CASE WHEN TYPE = "2" THEN 1 ELSE 0 END)*1.0 / COUNT() AS BRAND_TYPE_2_RATE
,SUM(CASE WHEN TYPE = "3" THEN 1 ELSE 0 END)*1.0 / COUNT() AS BRAND_TYPE_3_RATE
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END)*1.0 / COUNT() AS BRAND_TYPE_4_RATE
,SUM(CASE WHEN TYPE = "5" THEN 1 ELSE 0 END)*1.0 / COUNT() AS BRAND_TYPE_5_RATE
,SUM(CASE WHEN TYPE = "6" THEN 1 ELSE 0 END)*1.0 / COUNT() AS BRAND_TYPE_6_RATE
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END)*1.0 / SUM(CASE WHEN TYPE = "1" THEN 1 ELSE 0 END) AS BRAND_TYPE_1_4_RATE
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END)*1.0 / SUM(CASE WHEN TYPE = "2" THEN 1 ELSE 0 END) AS BRAND_TYPE_2_4_RATE
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END)*1.0 / SUM(CASE WHEN TYPE = "3" THEN 1 ELSE 0 END) AS BRAND_TYPE_3_4_RATE
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END)*1.0 / SUM(CASE WHEN TYPE = "5" THEN 1 ELSE 0 END) AS BRAND_TYPE_5_4_RATE
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END)*1.0 / SUM(CASE WHEN TYPE = "6" THEN 1 ELSE 0 END) AS BRAND_TYPE_6_4_RATE
from JDATA_ACTION_TBL
where time <= DATE('2016-04-10')
group by BRAND;

select count() from BRAND_CONVERSION_RATES_0201_0410;
-- 434

-- Cate level conversion rates
drop table if exists CATE_CONVERSION_RATES_0201_0410;
create table CATE_CONVERSION_RATES_0201_0410 as
select
CATE
,SUM(CASE WHEN TYPE = "1" THEN 1 ELSE 0 END) AS CATE_TYPE_1_CNT
,SUM(CASE WHEN TYPE = "2" THEN 1 ELSE 0 END) AS CATE_TYPE_2_CNT
,SUM(CASE WHEN TYPE = "3" THEN 1 ELSE 0 END) AS CATE_TYPE_3_CNT
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END) AS CATE_TYPE_4_CNT
,SUM(CASE WHEN TYPE = "5" THEN 1 ELSE 0 END) AS CATE_TYPE_5_CNT
,SUM(CASE WHEN TYPE = "6" THEN 1 ELSE 0 END) AS CATE_TYPE_6_CNT
,SUM(CASE WHEN TYPE = "1" THEN 1 ELSE 0 END)*1.0 / COUNT() AS CATE_TYPE_1_RATE
,SUM(CASE WHEN TYPE = "2" THEN 1 ELSE 0 END)*1.0 / COUNT() AS CATE_TYPE_2_RATE
,SUM(CASE WHEN TYPE = "3" THEN 1 ELSE 0 END)*1.0 / COUNT() AS CATE_TYPE_3_RATE
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END)*1.0 / COUNT() AS CATE_TYPE_4_RATE
,SUM(CASE WHEN TYPE = "5" THEN 1 ELSE 0 END)*1.0 / COUNT() AS CATE_TYPE_5_RATE
,SUM(CASE WHEN TYPE = "6" THEN 1 ELSE 0 END)*1.0 / COUNT() AS CATE_TYPE_6_RATE
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END)*1.0 / SUM(CASE WHEN TYPE = "1" THEN 1 ELSE 0 END) AS CATE_TYPE_1_4_RATE
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END)*1.0 / SUM(CASE WHEN TYPE = "2" THEN 1 ELSE 0 END) AS CATE_TYPE_2_4_RATE
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END)*1.0 / SUM(CASE WHEN TYPE = "3" THEN 1 ELSE 0 END) AS CATE_TYPE_3_4_RATE
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END)*1.0 / SUM(CASE WHEN TYPE = "5" THEN 1 ELSE 0 END) AS CATE_TYPE_5_4_RATE
,SUM(CASE WHEN TYPE = "4" THEN 1 ELSE 0 END)*1.0 / SUM(CASE WHEN TYPE = "6" THEN 1 ELSE 0 END) AS CATE_TYPE_6_4_RATE
from JDATA_ACTION_TBL
where time <= DATE('2016-04-10')
group by CATE;

select count() from CATE_CONVERSION_RATES_0201_0410;
-- 8

-- sku user conversion
drop table if exists SKU_RANK_0201_0410;
create table SKU_RANK_0201_0410 as
select
SKU_ID

-- brand level rank

-- cate level rank

-- sku level actions

-- cate level actions

-- brand level actions

-- User*SKU Level Signals
